# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fudspinbackend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://fudspin.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_897191e5ce4f4082a771daf4ab920c55 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_59e809aa74fb44a9a46ff94039ac792d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: fudspin.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_897191e5ce4f4082a771daf4ab920c55 }}/fudspinbackend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fudspinbackend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_86a426fb1948493b8c371f6ed47f21bb }}
        images: 'fudspin.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_897191e5ce4f4082a771daf4ab920c55 }}/fudspinbackend:${{ github.sha }}'